swagger: '2.0'
info:
  title: Blue Light Locations API
  description: API for getting the locations of all the campus blue light phones
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/blue-light-phones-api
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      parameters:
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'
  /blue-light-phones:
    get:
      summary: Get Blue Lights
      description: Latitude and Longitude information of all the campus Blue Lights
      responses:
        200:
          description: Response object containing Blue Light data
          schema:
            $ref: '#/definitions/ResultObject'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  ResultObject:
    properties:
      data:
        $ref: "#/definitions/ResourceObject"
  ResourceObject:
    properties:
      id:
        type: number
        format: integer
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
  Attributes:
    properties:
      blueLightPhones:
        type: array
        items:
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float
  Info:
    properties:
      name:
        type: string
        description: Name of the API.
      time:
        type: string
        description: Build time in ISO 8601 format.
      unixTime:
        type: integer
        description: Build time as milliseconds since the unix epoch.
      commit:
        type: string
        description: Git commit hash of the revision which was built.
      documentation:
        type: string
        description: Filename of the swagger specification for the API.
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
